# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    
    :test => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.130.1', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "router-net"},
               ]
            },
        }

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 4096
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public] 
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
          when "test"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            setenforce 0
            sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config 
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            service sshd restart
            yum update -y
            yum install nano epel-release -y
            yum install docker docker-compose -y
            systemctl start docker
            systemctl enable docker
            docker network create --subnet=10.6.0.0/24 --driver=bridge zabbix-net
#            docker pull zabbix/zabbix-server-mysql:centos-4.2.1
#            docker pull zabbix/zabbix-web-nginx-mysql:centos-4.2.1
#            docker pull mysql:5.7.26

            #для сервера заббикса
#            container_name=zab-mysql
#            mkdir -p /storage/${container_name}/data && mkdir /storage/${container_name}/config
            #https://hub.docker.com/_/mysql
            #в откртом виде передавать пароли - стрёмное дело. В продакшн случае можно упаковать или в файл или в секреты гитхаба/волта
#            docker run --name mysql -e MYSQL_ROOT_PASSWORD=mysql -d mysql:5.6            
            #https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql/
            #docker run --name some-zabbix-web-nginx-mysql -e DB_SERVER_HOST="some-mysql-server" -e MYSQL_USER="some-user" -e MYSQL_PASSWORD="some-password" -e ZBX_SERVER_HOST="some-zabbix-server" -e PHP_TZ="some-timezone" -d zabbix/zabbix-web-nginx-mysql:tag





            

            SHELL
          end

      end

    end
  
end
