# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {

    :cobbler => {
        :box_name => "centos/7",
        :box_version => "1905.1",
        :box_check_update => "false",
        :ip_addr => '192.168.20.10'
        },
    }

Vagrant.configure(2) do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "1024"]
                    needsController = false
            end

        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
            setenforce 0
#            reboot now
#            SHELL
#        end

#        config.vm.provision :reload

#        config.vm.provision "shell", inline: <<-SHELL
#            setenfoce 0 
            yum install -y epel-release
#            yum update -y
            yum makecache
            yum install -y cobbler cobbler-web dnsmasq syslinux pykickstart xinetd httpd dhcp debmirror pykickstart bind wget
            systemctl enable --now httpd
            systemctl enable --now cobblerd
            systemctl enable --now xinetd
            systemctl enable --now rsyncd
            cp /vagrant/conf/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf
            systemctl enable --now dhcpd
#            systemctl enable --now firewalld.service
            systemctl enable --now tftp.service
#            firewall-cmd --add-port=80/tcp --permanent
#            firewall-cmd --add-port=443/tcp --permanent
#            firewall-cmd --add-service=dhcp --permanent
#            firewall-cmd --add-port=69/tcp --permanent
#            firewall-cmd --add-port=69/udp --permanent
#            firewall-cmd --add-port=4011/udp --permanent
#            firewall-cmd --reload
            cp /etc/cobbler/settings{,.orig} 
            cp /vagrant/conf/cobbler/* /etc/cobbler/
            cobbler get-loaders
            sed -i "s/^@dists/#@dists/" /etc/debmirror.conf
            sed -i "s/^@arches/#@arches/" /etc/debmirror.conf
            yum install -y fence-agents 
        SHELL
        
        config.vm.provision :reload

        box.vm.provision "shell", inline: <<-SHELL
            systemctl restart cobblerd
            cobbler sync
            cobbler check

            # проверяем корректность настроек
            # должно быть:
            # No configuration problems found.  All systems go.

            ### подтягиваем ОС
#            wget https://mirror.yandex.ru/centos/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso
            mkdir /mnt/centos7 
            mount -t iso9660 -o loop,ro /vagrant/CentOS-7-x86_64-Minimal-1908.iso /mnt/centos7
            cp /vagrant/kickstarts/* /var/lib/cobbler/kickstarts/
            cobbler import --arch=x86_64 --path=/mnt/centos7 --name=CentOS7
            cobbler profile edit --name=CentOS7-x86_64 --kickstart=/var/lib/cobbler/kickstarts/CentOS7.ks
#            mkdir /mnt/centos8
#            wget http://mirror.logol.ru/centos/8.1.1911/isos/x86_64/CentOS-8.1.1911-x86_64-boot.iso
#            mount -t iso9660 -o loop,ro /tmp/CentOS-7-x86_64-Minimal-1908.iso /mnt/centos8
#            cobbler profile edit --name=CentOS7-x86_64 
            cobbler sync


            SHELL
  
        end
    end

end

#end
