# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {

    :cobbler => {
        :box_name => "centos/7",
        :box_version => "1905.1",
        :box_check_update => "false",
        :ip_addr => '192.168.20.10'
        },
	}

Vagrant.configure(2) do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "1024"]
                    needsController = false
            end

        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
            setenforce 0
            reboot now
            yum install -y epel-release
            yum update -y
            yum install -y cobbler cobbler-web dnsmasq syslinux pykickstart xinetd httpd dhcp debmirror pykickstart bind 
            systemctl enable --now cobblerd
            systemctl enable --now httpd
            systemctl enable --now xinetd
            systemctl enable --now rsyncd
            cp /vagrant/conf/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf
            systemctl enable --now dhcpd
            systemctl enable --now firewalld.service
            firewall-cmd --add-port=80/tcp --permanent
            firewall-cmd --add-port=443/tcp --permanent
            firewall-cmd --add-service=dhcp --permanent
            firewall-cmd --add-port=69/tcp --permanent
            firewall-cmd --add-port=69/udp --permanent
            firewall-cmd --add-port=4011/udp --permanent
            firewall-cmd --reload
            cp /etc/cobbler/settings{,.orig} 
            cp /vagrant/conf/cobbler/* /etc/cobbler/

            SHELL
  
        end
    end

end
